### ISSUE TITLE
hex2nix doesn't include old versions of packages

### ISSUE THREAD

**Issue by dipinhora** [erlang-nix/hex2nix#20]
I'm new to both nix and erlang so please forgive me if this is a silly question.

I ran hex2nix from master and it generated a `hex-packages.nix` file that doesn't contain older versions of some packages. In my case, I was looking for `phoenix_1_1_6` but the following are the only phoenix packages in the generated `hex-packages.nix` file (found by running `grep 'phoenix_[01].*=' hex-packages.nix`):

```
    phoenix_0_4_1 = callPackage
    phoenix_1_2_0 = callPackage
    phoenix_1_2_0_rc_0 = callPackage
    phoenix_1_2_0_rc_1 = callPackage
```

The hex.pm site lists many versions: https://hex.pm/packages/phoenix

Is this expected behavior?

**Comment by gleber** [comment]
Yes. By default it includes only the latest version and all versions which
are dependencies of other projects.

**Comment by dipinhora** [comment]
Ok. Thanks for the info.
