### ISSUE TITLE
Fatal errors

### ISSUE THREAD

**Issue by yurrriq** [erlang-nix/hex2nix#21]
With `<nixpkgs>` at [b349d4b](https://github.com/NixOS/nixpkgs/tree/b349d4b899a42edcd83cf7057e9d3f1c0833a741), I experience the following:

<details>
  <summary><code>nix-shell --pure -p hex2nix --run 'hex2nix -o pkgs/development/beam-modules'</code>
</summary>
<pre>
Pulling Hex Registry From https://raw.githubusercontent.com/erlang-nix/hex-pm-registry-snapshots/master/registry.ets.gz to /var/folders/6r/km807r7d10gg22hcn82t671r0000gn/T/tmp.XzZtdnREz4
File uncompressed to /var/folders/6r/km807r7d10gg22hcn82t671r0000gn/T/tmp.XzZtdnREz4/registry.ets
Discarding malformed detail: {'$$installs2$$',
                                 [{<<"0.0.1">>,[<<"0.13.0-dev">>]},
                                  {<<"0.1.0">>,[<<"0.13.1-dev">>]},
                                  {<<"0.1.1">>,[<<"0.13.1-dev">>]},
                                  {<<"0.1.2">>,[<<"0.13.1-dev">>]},
                                  {<<"0.2.0">>,[<<"0.13.2-dev">>]},
                                  {<<"0.2.1">>,[<<"0.13.2">>]},
                                  {<<"0.2.2">>,[<<"0.13.2">>]},
                                  {<<"0.2.3">>,[<<"0.13.2">>]},
                                  {<<"0.2.4">>,[<<"0.13.3">>]},
                                  {<<"0.2.5">>,[<<"0.14.1-dev">>]},
                                  {<<"0.3.0">>,[<<"0.14.2-dev">>]},
                                  {<<"0.3.1">>,[<<"0.14.2-dev">>]},
                                  {<<"0.3.2">>,[<<"0.14.2">>]},
                                  {<<"0.3.3">>,[<<"0.14.3">>]},
                                  {<<"0.4.0">>,[<<"0.15.0-dev">>]},
                                  {<<"0.4.1">>,[<<"0.15.0">>]},
                                  {<<"0.4.2">>,[<<"0.15.0">>]},
                                  {<<"0.4.3">>,[<<"1.0.0-rc1">>]},
                                  {<<"0.5.0">>,[<<"1.0.0">>]},
                                  {<<"0.6.0">>,[<<"1.0.0">>]},
                                  {<<"0.6.1">>,[<<"1.0.0">>]},
                                  {<<"0.6.2">>,[<<"1.0.0">>]},
                                  {<<"0.7.0">>,[<<"1.0.0">>]},
                                  {<<"0.7.1">>,[<<"1.0.0">>]},
                                  {<<"0.7.2">>,[<<"1.0.0">>]},
                                  {<<"0.7.3">>,[<<"1.0.0">>]},
                                  {<<"0.7.4">>,[<<"1.0.0">>]},
                                  {<<"0.7.5">>,[<<"1.0.0">>]},
                                  {<<"0.8.0">>,[<<"1.0.0">>]},
                                  {<<"0.8.1">>,[<<"1.0.0">>]},
                                  {<<"0.8.2">>,[<<"1.0.0">>]},
                                  {<<"0.8.3">>,[<<"1.0.0">>]},
                                  {<<"0.9.0">>,[<<"1.0.0">>,<<"1.1.0">>]},
                                  {<<"0.10.0">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.10.2">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.10.3">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.10.4">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.0">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.1">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.2">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.3">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.4">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.11.5">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.12.0">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.12.1">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>]},
                                  {<<"0.13.0">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>,
                                    <<"1.3.0">>]},
                                  {<<"0.13.1">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>,
                                    <<"1.3.0">>]},
                                  {<<"0.13.2">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>,
                                    <<"1.3.0">>]},
                                  {<<"0.14.0">>,
                                   [<<"1.0.0">>,<<"1.1.0">>,<<"1.2.0">>,
                                    <<"1.3.0">>]}]}
Discarding malformed detail: {'$$version$$',4}
Unable to resolve dependency (inaka_mixer = 0.1.4) for hexer-0.0.1
Unable to resolve dependency (plug = ~> 1.0) for plug_best-0.1.3
Unable to resolve dependency (gun ~> 1.0.0-pre.1) for tanegashima-0.0.11
Unable to resolve dependency (plug = ~> 1.0) for plug_canonical_host-0.2.3
Unable to resolve dependency (ssl_verify_hostname = <= 1.0.6) for fintex-0.3.0
Fetching phoenix_jsroutes 0.0.4 details from hex.pm.
escript: exception error: no match of right hand side value
                 {ok,"400",
                     [{"Connection","keep-alive"},
                      {"Server","Cowboy"},
                      {"Date","Tue, 13 Jun 2017 04:19:28 GMT"},
                      {"Content-Length","56"},
                      {"Content-Type",
                       "application/vnd.hex+json; charset=utf-8"},
                      {"Cache-Control","max-age=0, private, must-revalidate"},
                      {"Strict-Transport-Security","max-age=31536000"},
                      {"Vary","accept-encoding"},
                      {"Via","1.1 vegur"}],
                     "{\"status\":400,\"message\":\"User-Agent header is requried\"}"}
  in function  h2n_fetcher:get_app_detail_from_hex_pm/1 (/private/var/tmp/nix-build-hex2nix-0.0.5.drv-0/hex2nix-0.0.5-src/_build/default/lib/hex2nix/src/h2n_fetcher.erl, line 174)
  in call from h2n_fetcher:decorate_app/2 (/private/var/tmp/nix-build-hex2nix-0.0.5.drv-0/hex2nix-0.0.5-src/_build/default/lib/hex2nix/src/h2n_fetcher.erl, line 145)
  in call from lists:filtermap/2 (lists.erl, line 1316)
  in call from hex2nix:do_main/1 (/private/var/tmp/nix-build-hex2nix-0.0.5.drv-0/hex2nix-0.0.5-src/_build/default/lib/hex2nix/src/hex2nix.erl, line 103)
  in call from escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1
  in call from init:start_em/1
</pre>
</details>

**Comment by gleber** [comment]
This is fixed by https://github.com/erlang-nix/hex2nix/pull/19, but nixpkgs refers to version 0.05 which does not yet include this change.

**Comment by yurrriq** [comment]
Cool, thanks. Is there a PR on nixpkgs to update it yet?

**Comment by yurrriq** [comment]
Looks like no. Can we push a new release here and then solve https://github.com/NixOS/nixpkgs/issues/26544?

**Comment by gleber** [comment]
I'll push 0.06 version here in 20 minutes

**Comment by gleber** [comment]
https://github.com/erlang-nix/hex2nix/tree/0.0.6 is out. Feel free to update hex2nix nixpkgs definition.

**Comment by yurrriq** [comment]
0.0.6 still doesn't work for me:

```
Fetching mike_hoffert 0.0.7 details from hex.pm.
escript: exception error: no case clause matching
                 {ok,"404",
                     [{"Connection","keep-alive"},
                      {"Server","Cowboy"},
                      {"Date","Tue, 13 Jun 2017 09:17:44 GMT"},
                      {"Content-Length","41"},
                      {"Content-Type",
                       "application/vnd.hex+json; charset=utf-8"},
                      {"Cache-Control","max-age=0, private, must-revalidate"},
                      {"Strict-Transport-Security","max-age=31536000"},
                      {"X-Ratelimit-Limit","100"},
                      {"X-Ratelimit-Remaining","87"},
                      {"X-Ratelimit-Reset","1497345480"},
                      {"Vary","accept-encoding"},
                      {"Via","1.1 vegur"}],
                     "{\"status\":404,\"message\":\"Page not found\"}"}
```
