### ISSUE TITLE
Few packages do not have deps detected correctly

### ISSUE THREAD

**Issue by gleber** [erlang-nix/hex2nix#4]
https://hex.pm/packages/jc has no listed deps on Hex, but according to this build log rebar sees more deps:
http://ix.io/nt5

**Comment by gleber** [comment]
@ericbmerritt FYI

**Comment by ericbmerritt** [comment]
This is problematic. We do download the contents eventually but thats well after we have resolved dependencies. This looks like a combination of a bug in hex and the maintainer pushing a bad set. I would suggest that unless we start seeing this more. we let the upstream fix it and continue to assume that hex is correct.

**Comment by ericbmerritt** [comment]
I think this is closed unless we can verify that it continues.
